import { MenuItem } from "@/app/type";

export const dummyData: MenuItem[] = [
  {
    id: "1",
    name: {
      ko: "김치찌개",
      en: "Kimchi Stew",
      ja: "キムチチゲ",
      zh: "泡菜汤",
    },
    description: {
      ko: "돼지고기와 신선한 김치로 만든 전통 찌개",
      en: "Traditional stew made with pork and fresh kimchi",
      ja: "豚肉と新鮮なキムチで作った伝統的な韓国鍋",
      zh: "用猪肉和新鲜泡菜制作的传统汤",
    },
    price: 8000,
    imageUrl: "",
    category: "찌개",
    allergens: {
      ko: ["돼지고기", "고추"],
      en: ["pork", "red hot chili pepper"],
      ja: ["豚肉", "唐辛子"],
      zh: ["猪肉", "辣椒"],
    },
    spicyLevel: 2,
    preparationTime: 15,
  },
  {
    id: "2",
    name: {
      ko: "된장찌개",
      en: "Soybean Paste Stew",
      ja: "味噌チゲ",
      zh: "大酱汤",
    },
    description: {
      ko: "신선한 두부와 채소가 들어간 된장찌개",
      en: "Soybean paste stew with fresh tofu and vegetables",
      ja: "新鮮な豆腐と野菜が入った味噌チゲ",
      zh: "加入新鲜豆腐和蔬菜的大酱汤",
    },
    price: 7000,
    imageUrl: "",
    category: "찌개",
    allergens: {
      ko: ["대두"],
      en: ["soybean"],
      ja: ["大豆"],
      zh: ["大豆"],
    },
    spicyLevel: 1,
    preparationTime: 15,
  },
  {
    id: "3",
    name: {
      ko: "닭 한마리",
      en: "One chicken",
      ja: "一羽の鶏",
      zh: "一只鸡",
    },
    description: {
      ko: "신선한 닭고기와 채소가 들어간 닭찌개",
      en: "Chicken stew with fresh chicken and vegetables",
      ja: "新鮮な鶏肉と野菜が入った鶏チゲ",
      zh: "加入新鲜鸡肉和蔬菜的鸡肉汤",
    },
    price: 15000,
    imageUrl: "",
    category: "찌개",
    allergens: {
      ko: ["닭고기", "고추"],
      en: ["chicken", "red hot chili pepper"],
      ja: ["鶏肉", "唐辛子"],
      zh: ["鸡肉", "辣椒"],
    },
    isPopular: true,
    spicyLevel: 2,
    preparationTime: 20,
  },
  {
    id: "4",
    name: {
      ko: "김밥",
      en: "Kimbab",
      ja: "握り寿司",
      zh: "寿司卷",
    },
    description: {
      ko: "신선한 김밥",
      en: "Fresh kimbab with crab and sausage",
      ja: "新鮮な握り寿司",
      zh: "新鲜的手卷寿司",
    },
    price: 5000,
    imageUrl: "",
    category: "밥",
    allergens: {
      ko: ["게"],
      en: ["crab"],
      ja: ["カニ"],
      zh: ["螃蟹"],
    },
    isPopular: true,
    spicyLevel: 1,
    preparationTime: 5,
  },
  {
    id: "5",
    name: {
      ko: "야채 김밥",
      en: "Vegan kimbab",
      ja: "野菜キンバップ",
      zh: "蔬菜紫菜包饭",
    },
    description: {
      ko: "채식주의자를 위한 야채 김밥",
      en: "For sale: vegetable kimbab, never meat",
      ja: "ベジタリアンのための野菜キンバップ",
      zh: "为素食者准备的蔬菜紫菜包饭",
    },
    price: 4000,
    imageUrl: "",
    category: "밥",
    allergens: {},
    isPopular: true,
    spicyLevel: 1,
    preparationTime: 5,
  },
];
